### ISSUE TITLE
Resources paths cannot end with '/'

### ISSUE THREAD

**Issue by DriesSchaumont** [viash-io/viash#175]
When a `path` under `resources` does not end with a `/` (`- path: foo`), using a component succeeds.
```
curl -fsSL get.viash.io | bash
mkdir foo
echo lala > foo/bar

cat > works.vsh.yaml << 'HERE'
functionality:
  name: myscript
  resources:
    - type: bash_script
      path: script.sh
      text: |
        tree .
    - path: foo
HERE

./bin/viash run works.vsh.yaml
```
However, using a slash (`- path: foo/`):

```
cat > noworks.vsh.yaml << 'HERE'
functionality:
  name: myscript
  resources:
    - type: bash_script
      path: script.sh
      text: |
        tree .
    - path: foo/
HERE

./bin/viash run noworks.vsh.yaml
```
The component fails with the following output:
```
Files and logs are stored at '/tmp/viash_myscript17260480228839751784'
Unexpected error occurred! If you think this is a bug, please post
create an issue at https://github.com/viash-io/viash/issues containing
a reproducible example and the stack trace below.

viash - 0.5.14
Stacktrace:
java.io.IOException: Cannot run program "/tmp/viash_myscript17260480228839751784/myscript": error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
	at scala.sys.process.ProcessBuilderImpl$Simple.run(ProcessBuilderImpl.scala:75)
	at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.run(ProcessBuilderImpl.scala:106)
	at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.$anonfun$runBuffered$1(ProcessBuilderImpl.scala:154)
	at scala.runtime.java8.JFunction0$mcI$sp.apply(JFunction0$mcI$sp.java:23)
	at scala.sys.process.ProcessLogger$$anon$1.buffer(ProcessLogger.scala:103)
	at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.runBuffered(ProcessBuilderImpl.scala:154)
	at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.$bang(ProcessBuilderImpl.scala:120)
	at com.dataintuitive.viash.ViashRun$.apply(ViashRun.scala:54)
	at com.dataintuitive.viash.Main$.internalMain(Main.scala:72)
	at com.dataintuitive.viash.Main$.main(Main.scala:40)
	at com.dataintuitive.viash.Main.main(Main.scala)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:314)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:244)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)
	... 12 more
```

**Comment by Grifs** [comment]
Solved in Viash 0.5.15
