### ISSUE TITLE
VIASH_TEMP must be absolute

### ISSUE THREAD

**Issue by rcannood** [viash-io/viash#242]
Running `viash test` with a `VIASH_TEMP` that is relative results in an exception being thrown:

```
VIASH_TEMP=foo viash test src/test/resources/testbash/config.vsh.yaml 
Running tests in temporary directory: 'foo/viash_test_testbash6365763974915076903'
====================================================================
+foo/viash_test_testbash6365763974915076903/test_check_outputs/test_executable
Unexpected error occurred! If you think this is a bug, please post
create an issue at https://github.com/viash-io/viash/issues containing
a reproducible example and the stack trace below.

viash - 0.6.0
Stacktrace:
java.io.IOException: Cannot run program "foo/viash_test_testbash6365763974915076903/test_check_outputs/test_executable" (in directory "foo/viash_test_testbash6365763974915076903/test_check_outputs"): error=2, No such file or directory
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
        at scala.sys.process.ProcessBuilderImpl$Simple.run(ProcessBuilderImpl.scala:75)
        at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.run(ProcessBuilderImpl.scala:106)
        at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.$anonfun$runBuffered$1(ProcessBuilderImpl.scala:154)
        at scala.runtime.java8.JFunction0$mcI$sp.apply(JFunction0$mcI$sp.java:23)
        at scala.sys.process.ProcessLogger$$anon$1.buffer(ProcessLogger.scala:103)
        at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.runBuffered(ProcessBuilderImpl.scala:154)
        at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.$bang(ProcessBuilderImpl.scala:120)
        at io.viash.ViashTest$.$anonfun$runTests$4(ViashTest.scala:245)
        at scala.collection.immutable.List.map(List.scala:293)
        at io.viash.ViashTest$.runTests(ViashTest.scala:177)
        at io.viash.ViashTest$.apply(ViashTest.scala:70)
        at io.viash.Main$.internalMain(Main.scala:85)
        at io.viash.Main$.main(Main.scala:38)
        at io.viash.Main.main(Main.scala)
Caused by: java.io.IOException: error=2, No such file or directory
        at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
        at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:340)
        at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:271)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
        ... 15 more
```

Setting ```VIASH_TEMP=`pwd`/foo``` solves the issue, so `VIASH_TEMP` should be made absolute before doing anything with it.

**Comment by rcannood** [comment]
Fixed by #244
