### ISSUE TITLE
Spaces in path to config file results in java.net.URISyntaxException

### ISSUE THREAD

**Issue by BlackDragonBE** [viash-io/viash#32]
Error:

```
Exception in thread "main" java.net.URISyntaxException: Illegal character in path at index 34: file:///home/ericvdkerckhove/viash tests/hello_world/config.vsh.yaml
	at java.base/java.net.URI$Parser.fail(URI.java:2913)
	at java.base/java.net.URI$Parser.checkChars(URI.java:3084)
	at java.base/java.net.URI$Parser.parseHierarchical(URI.java:3166)
	at java.base/java.net.URI$Parser.parse(URI.java:3114)
	at java.base/java.net.URI.<init>(URI.java:600)
	at com.dataintuitive.viash.helpers.IO$.uri(IO.scala:51)
	at com.dataintuitive.viash.config.Config$.read(Config.scala:71)
	at com.dataintuitive.viash.Main$.readConfig(Main.scala:87)
	at com.dataintuitive.viash.Main$.main(Main.scala:47)
	at com.dataintuitive.viash.Main.main(Main.scala)
```

Steps to reproduce:

1. Copy the "hello world" example folder locally to a folder with a space in it: https://github.com/data-intuitive/viash_docs/tree/master/examples/hello_world 
2. Do a `viash run` targeting the config.vsh.yaml file. E.g.: `viash run '/home/ericvdkerckhove/viash tests/hello_world/config.vsh.yaml'`

**Comment by Grifs** [comment]
solved in v0.5.12
