### ISSUE TITLE
passing viash config as URL is broken

### ISSUE THREAD

**Issue by Grifs** [viash-io/viash#338]
With the latest versions
`viash config view https://raw.githubusercontent.com/viash-io/viash_project_template/main/src/demo/remove_comments/config.vsh.yaml`
is broken:
```
Unexpected error occurred! If you think this is a bug, please post
create an issue at https://github.com/viash-io/viash/issues containing
a reproducible example and the stack trace below.

viash - 0.6.2
Stacktrace:
java.nio.file.FileSystemNotFoundException: Provider "https" not installed
	at java.base/java.nio.file.Path.of(Path.java:212)
	at java.base/java.nio.file.Paths.get(Paths.java:98)
	at io.viash.config.Config$.read(Config.scala:190)
	at io.viash.Main$.readConfig(Main.scala:218)
	at io.viash.Main$.internalMain(Main.scala:154)
	at io.viash.Main$.main(Main.scala:39)
	at io.viash.Main.main(Main.scala)
```

`VIASH_VERSION=0.6.3 viash config view https://raw.githubusercontent.com/viash-io/viash_project_template/main/src/demo/remove_comments/config.vsh.yaml` still works

`git bisect` pointed me to `b9492ec13c314e05526433b9063124094f4f588f` from 2022-10-30 what this broke

**Comment by Grifs** [comment]
Fixed in Viash 0.6.8
