### ISSUE TITLE
Race condition when calling ViashBuild

### ISSUE THREAD

**Issue by ddemaeyer** [viash-io/viash#43]
Running a build on a large multi-core server will result in a race condition 

```
  Suppressed: java.io.IOException: Cannot run program "target/docker/transfer/tobioturing/tobioturing": error=26, Text file busy
                        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
                        at scala.sys.process.ProcessBuilderImpl$Simple.run(ProcessBuilderImpl.scala:75)
                        at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.run(ProcessBuilderImpl.scala:106)
                        at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.$anonfun$runBuffered$1(ProcessBuilderImpl.scala:154)
                        at scala.runtime.java8.JFunction0$mcI$sp.apply(JFunction0$mcI$sp.java:23)
                        at scala.sys.process.ProcessLogger$$anon$1.buffer(ProcessLogger.scala:103)
                        at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.runBuffered(ProcessBuilderImpl.scala:154)
                        at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.$bang(ProcessBuilderImpl.scala:120)
                        at com.dataintuitive.viash.ViashBuild$.apply(ViashBuild.scala:119)
                        at com.dataintuitive.viash.ViashNamespace$.$anonfun$build$1(ViashNamespace.scala:49)
                        at com.dataintuitive.viash.ViashNamespace$.$anonfun$build$1$adapted(ViashNamespace.scala:35)
                        at scala.collection.Iterator.foreach(Iterator.scala:941)
```

The main exception here is in com.dataintuitive.viash.ViashBuild$.apply(ViashBuild.scala:119): 

```
110:    if (writeMeta) {
111:      IO.writeResources(configYaml :: fun.resources.getOrElse(Nil), dir)
112:    } else {
113:      IO.writeResources(fun.resources.getOrElse(Nil), dir)
114:   }
115:
116:    // if '--setup' was passed, run './executable ---setup'
117:    if (setup && exec_path.isDefined) {
118:      val cmd = Array(exec_path.get, "---setup")
119:      val _ = Process(cmd).!(ProcessLogger(println, println))
120:   }
```
The problem is thus that the Process call (line 119) is performed on a file that does not seems to have been completely written. In essence the root cause is probably that the files written in line 110 or 113 have not finished yet. 

Going deeper in the call stack results finally in the calling of the Files nio:

```
 Files.write(path, text.getBytes(StandardCharsets.UTF_8))
```

This could be related to this [bug](https://bugs.openjdk.java.net/browse/JDK-8068370). However this one is pretty old but still open and affects java 7, 8, and 9

The server is currently running openjdk 1.8.0_275 which was released November 2020. Updating to openjdk 1.8.0_282 solved the problem. 

Adding this for documentation.

**Comment by rcannood** [comment]
```
$ bin/project_build
Exception in thread "main" java.io.IOException: Cannot run program "target/docker/convert/h5adtopseudobulks/h5adtopseudobulks": error=26, Text file busy
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
	at scala.sys.process.ProcessBuilderImpl$Simple.run(ProcessBuilderImpl.scala:75)
	at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.run(ProcessBuilderImpl.scala:106)
	at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.$anonfun$runBuffered$1(ProcessBuilderImpl.scala:154)
	at scala.runtime.java8.JFunction0$mcI$sp.apply(JFunction0$mcI$sp.java:23)
	at scala.sys.process.ProcessLogger$$anon$1.buffer(ProcessLogger.scala:103)
	at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.runBuffered(ProcessBuilderImpl.scala:154)
	at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.$bang(ProcessBuilderImpl.scala:120)
	at com.dataintuitive.viash.ViashBuild$.apply(ViashBuild.scala:119)
	at com.dataintuitive.viash.ViashNamespace$.$anonfun$build$1(ViashNamespace.scala:49)
	at com.dataintuitive.viash.ViashNamespace$.$anonfun$build$1$adapted(ViashNamespace.scala:35)
	at scala.collection.Iterator.foreach(Iterator.scala:941)
	at scala.collection.Iterator.foreach$(Iterator.scala:941)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
	at scala.collection.parallel.ParIterableLike$Foreach.leaf(ParIterableLike.scala:974)
	at scala.collection.parallel.Task.$anonfun$tryLeaf$1(Tasks.scala:53)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.util.control.Breaks$$anon$1.catchBreak(Breaks.scala:67)
	at scala.collection.parallel.Task.tryLeaf(Tasks.scala:56)
	at scala.collection.parallel.Task.tryLeaf$(Tasks.scala:50)
	at scala.collection.parallel.ParIterableLike$Foreach.tryLeaf(ParIterableLike.scala:971)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.internal(Tasks.scala:170)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.internal$(Tasks.scala:157)
	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.internal(Tasks.scala:440)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute(Tasks.scala:150)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute$(Tasks.scala:149)
	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:440)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
	Suppressed: java.io.IOException: Cannot run program "target/docker/mapping/cellranger_vdj/cellranger_vdj": error=26, Text file busy
		at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
		at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
		at scala.sys.process.ProcessBuilderImpl$Simple.run(ProcessBuilderImpl.scala:75)
		at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.run(ProcessBuilderImpl.scala:106)
		at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.$anonfun$runBuffered$1(ProcessBuilderImpl.scala:154)
		at scala.runtime.java8.JFunction0$mcI$sp.apply(JFunction0$mcI$sp.java:23)
		at scala.sys.process.ProcessLogger$$anon$1.buffer(ProcessLogger.scala:103)
		at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.runBuffered(ProcessBuilderImpl.scala:154)
		at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.$bang(ProcessBuilderImpl.scala:120)
		at com.dataintuitive.viash.ViashBuild$.apply(ViashBuild.scala:119)
		at com.dataintuitive.viash.ViashNamespace$.$anonfun$build$1(ViashNamespace.scala:49)
		at com.dataintuitive.viash.ViashNamespace$.$anonfun$build$1$adapted(ViashNamespace.scala:35)
		at scala.collection.Iterator.foreach(Iterator.scala:941)
		at scala.collection.Iterator.foreach$(Iterator.scala:941)
		at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
		at scala.collection.parallel.ParIterableLike$Foreach.leaf(ParIterableLike.scala:974)
		at scala.collection.parallel.Task.$anonfun$tryLeaf$1(Tasks.scala:53)
		at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
		at scala.util.control.Breaks$$anon$1.catchBreak(Breaks.scala:67)
		at scala.collection.parallel.Task.tryLeaf(Tasks.scala:56)
		at scala.collection.parallel.Task.tryLeaf$(Tasks.scala:50)
		at scala.collection.parallel.ParIterableLike$Foreach.tryLeaf(ParIterableLike.scala:971)
		at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.internal(Tasks.scala:160)
		... 11 more
	Caused by: java.io.IOException: error=26, Text file busy
		at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
		at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:340)
		at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:271)
		at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
		... 33 more
Caused by: java.io.IOException: error=26, Text file busy
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:340)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:271)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
	... 33 more
```

**Comment by rcannood** [comment]
Similar to #47. Closing this one as it is solved.
