### ISSUE TITLE
Catch MalformedInputException

### ISSUE THREAD

**Issue by rcannood** [viash-io/viash#441]
When there is a non-ascii character in the config and the system (for some reason) does not support it, the error message is quite unreadable.

Example `config.vsh.yaml`:

```yaml
functionality:
  name: foo
  description: Ohnö!
```

Command:

```bash
LANG=C viash config view config.vsh.yaml
```

Expected output, something like:

    Could not read config file at '...'. This is likely due to a bug in the current version of Java with non-ASCII characters.

Output:
  
    Unexpected error occurred! If you think this is a bug, please post
    create an issue at https://github.com/viash-io/viash/issues containing
    a reproducible example and the stack trace below.
    
    viash - 0.7.4
    Stacktrace:
    java.nio.charset.MalformedInputException: Input length = 1
            at java.base/java.nio.charset.CoderResult.throwException(CoderResult.java:274)
            at java.base/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
            at java.base/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:188)
            at java.base/java.io.InputStreamReader.read(InputStreamReader.java:177)
            at java.base/java.io.BufferedReader.fill(BufferedReader.java:162)
            at java.base/java.io.BufferedReader.readLine(BufferedReader.java:329)
            at java.base/java.io.BufferedReader.readLine(BufferedReader.java:396)
            at scala.io.BufferedSource$BufferedLineIterator.hasNext(BufferedSource.scala:73)
            at scala.collection.Iterator.isEmpty(Iterator.scala:466)
            at scala.collection.Iterator.isEmpty$(Iterator.scala:466)
            at scala.collection.AbstractIterator.isEmpty(Iterator.scala:1300)
            at scala.collection.IterableOnceOps.mkString(IterableOnce.scala:1165)
            at scala.collection.IterableOnceOps.mkString$(IterableOnce.scala:1164)
            at scala.collection.AbstractIterator.mkString(Iterator.scala:1300)
            at scala.collection.IterableOnceOps.mkString(IterableOnce.scala:1179)
            at scala.collection.IterableOnceOps.mkString$(IterableOnce.scala:1179)
            at scala.collection.AbstractIterator.mkString(Iterator.scala:1300)
            at io.viash.helpers.IO$.read(IO.scala:109)
            at io.viash.helpers.circe.RichJson.$anonfun$inherit$5(RichJson.scala:193)
            at scala.collection.immutable.List.map(List.scala:246)
            at io.viash.helpers.circe.RichJson.inherit(RichJson.scala:189)
            at io.viash.helpers.circe.RichJson.$anonfun$inherit$8(RichJson.scala:219)
            at scala.collection.immutable.Vector1.map(Vector.scala:1911)
            at scala.collection.immutable.Vector1.map(Vector.scala:377)
            at io.viash.helpers.circe.RichJson.inherit(RichJson.scala:219)
            at io.viash.helpers.circe.RichJson.$anonfun$inherit$7(RichJson.scala:215)
            at io.circe.JsonObject$MapAndVectorJsonObject.$anonfun$mapValues$1(JsonObject.scala:428)
            at scala.collection.StrictOptimizedMapOps.map(StrictOptimizedMapOps.scala:28)
            at scala.collection.StrictOptimizedMapOps.map$(StrictOptimizedMapOps.scala:27)
            at scala.collection.immutable.HashMap.map(HashMap.scala:39)
            at io.circe.JsonObject$MapAndVectorJsonObject.mapValues(JsonObject.scala:427)
            at io.viash.helpers.circe.RichJson.inherit(RichJson.scala:215)
            at io.viash.helpers.circe.RichJson.$anonfun$inherit$7(RichJson.scala:215)
            at io.circe.JsonObject$MapAndVectorJsonObject.$anonfun$mapValues$1(JsonObject.scala:428)
            at scala.collection.Iterator$$anon$9.next(Iterator.scala:584)
            at scala.collection.mutable.Growable.addAll(Growable.scala:62)
            at scala.collection.mutable.Growable.addAll$(Growable.scala:57)
            at scala.collection.immutable.MapBuilderImpl.addAll(Map.scala:690)
            at scala.collection.immutable.Map$.from(Map.scala:641)
            at scala.collection.immutable.Map$.from(Map.scala:171)
            at scala.collection.MapOps.map(Map.scala:299)
            at scala.collection.MapOps.map$(Map.scala:299)
            at scala.collection.AbstractMap.map(Map.scala:405)
            at io.circe.JsonObject$MapAndVectorJsonObject.mapValues(JsonObject.scala:427)
            at io.viash.helpers.circe.RichJson.inherit(RichJson.scala:215)
            at io.viash.config.Config$.readFromUri(Config.scala:209)
            at io.viash.config.Config$.read(Config.scala:182)
            at io.viash.Main$.readConfig(Main.scala:365)
            at io.viash.Main$.mainCLI(Main.scala:290)
            at io.viash.Main$.mainCLIOrVersioned(Main.scala:117)
            at io.viash.Main$.main(Main.scala:64)
            at io.viash.Main.main(Main.scala)

**Comment by Grifs** [comment]
Solved in Viash 0.7.5
