### ISSUE TITLE
Stacktrace error in `viash ns list`

### ISSUE THREAD

**Issue by rcannood** [viash-io/viash#545]
Haven't had the time to take a look at the cause.

In `openproblems-bio/openproblems-v2`, I'm getting this error:

    $ viash ns list -q 'batch_integration/workflows/run_benchmark'
    Unexpected error occurred! If you think this is a bug, please post
    create an issue at https://github.com/viash-io/viash/issues containing
    a reproducible example and the stack trace below.
    
    viash - 0.8.0-RC2
    Stacktrace:
    java.util.NoSuchElementException: None.get
            at scala.None$.get(Option.scala:627)
            at scala.None$.get(Option.scala:626)
            at io.viash.helpers.DependencyResolver$.$anonfun$findLocalConfig$4(DependencyResolver.scala:157)
            at scala.Option.map(Option.scala:242)
            at io.viash.helpers.DependencyResolver$.findLocalConfig(DependencyResolver.scala:150)
            at io.viash.helpers.DependencyResolver$.$anonfun$modifyConfig$18(DependencyResolver.scala:92)
            at scala.collection.immutable.List.map(List.scala:246)
            at io.viash.helpers.DependencyResolver$.$anonfun$modifyConfig$17(DependencyResolver.scala:87)
            at io.viash.lenses.FunctionalityLenses$$anon$1.$anonfun$modify$1(FunctionalityLenses.scala:26)
            at io.viash.lenses.ConfigLenses$$anon$1.$anonfun$modify$1(ConfigLenses.scala:29)
            at io.viash.helpers.DependencyResolver$.modifyConfig(DependencyResolver.scala:102)
            at io.viash.Main$.handleSingleConfigDependency(Main.scala:532)
            at io.viash.Main$.$anonfun$namespaceDependencies$2(Main.scala:514)
            at scala.util.Try$.apply(Try.scala:210)
            at io.viash.Main$.$anonfun$namespaceDependencies$1(Main.scala:514)
            at scala.collection.immutable.List.map(List.scala:250)
            at io.viash.Main$.namespaceDependencies(Main.scala:511)
            at io.viash.Main$.mainCLI(Main.scala:293)
            at io.viash.Main$.mainCLIOrVersioned(Main.scala:123)
            at io.viash.Main$.main(Main.scala:58)
            at io.viash.Main.main(Main.scala)

**Comment by Grifs** [comment]
Solved in Viash 0.8.0-RC3
