### ISSUE TITLE
[BUG] `viash ns test` `-p native` fails to parse resources with paths relative to project root.

### ISSUE THREAD

**Issue by DriesSchaumont** [viash-io/viash#648]
### What happened?

When running `viash ns test -p native`, I get the following error. The error does not occur when using `-p docker`
```
java.lang.RuntimeException: One of the resources is relative to the project root (/src/authors/dries_schaumont.yaml), but no project config file (_viash.yaml) could be found.
        at io.viash.helpers.IO$.resolveProjectPath(IO.scala:326)
        at io.viash.helpers.circe.RichJson.$anonfun$inherit$3(RichJson.scala:169)
        at scala.collection.immutable.List.map(List.scala:246)
        at io.viash.helpers.circe.RichJson.inherit(RichJson.scala:165)
        at io.viash.helpers.circe.RichJson.$anonfun$inherit$8(RichJson.scala:223)
        at scala.collection.immutable.Vector1.map(Vector.scala:1911)
        at scala.collection.immutable.Vector1.map(Vector.scala:377)
        at io.viash.helpers.circe.RichJson.inherit(RichJson.scala:223)
        at io.viash.helpers.circe.RichJson.$anonfun$inherit$7(RichJson.scala:219)
        at io.circe.JsonObject$MapAndVectorJsonObject.$anonfun$mapValues$1(JsonObject.scala:428)
        at scala.collection.StrictOptimizedMapOps.map(StrictOptimizedMapOps.scala:28)
        at scala.collection.StrictOptimizedMapOps.map$(StrictOptimizedMapOps.scala:27)
        at scala.collection.immutable.HashMap.map(HashMap.scala:39)
        at io.circe.JsonObject$MapAndVectorJsonObject.mapValues(JsonObject.scala:427)
        at io.viash.helpers.circe.RichJson.inherit(RichJson.scala:219)
        at io.viash.helpers.circe.RichJson.$anonfun$inherit$7(RichJson.scala:219)
        at io.circe.JsonObject$MapAndVectorJsonObject.$anonfun$mapValues$1(JsonObject.scala:428)
        at scala.collection.Iterator$$anon$9.next(Iterator.scala:584)
        at scala.collection.mutable.Growable.addAll(Growable.scala:62)
        at scala.collection.mutable.Growable.addAll$(Growable.scala:57)
        at scala.collection.immutable.MapBuilderImpl.addAll(Map.scala:690)
        at scala.collection.immutable.Map$.from(Map.scala:641)
        at scala.collection.immutable.Map$.from(Map.scala:171)
        at scala.collection.MapOps.map(Map.scala:299)
        at scala.collection.MapOps.map$(Map.scala:299)
        at scala.collection.AbstractMap.map(Map.scala:405)
        at io.circe.JsonObject$MapAndVectorJsonObject.mapValues(JsonObject.scala:427)
        at io.viash.helpers.circe.RichJson.inherit(RichJson.scala:219)
        at io.viash.config.Config$.readFromUri(Config.scala:206)
        at io.viash.config.Config$.read(Config.scala:180)
        at io.viash.Main$.readConfig(Main.scala:419)
        at io.viash.Main$.mainCLI(Main.scala:224)
        at io.viash.Main$.mainCLIOrVersioned(Main.scala:123)
        at io.viash.Main$.main(Main.scala:58)
        at io.viash.Main.main(Main.scala)
```

### Steps to reproduce

```bash
git clone https://github.com/openpipelines-bio/openpipeline.git
cd openpipeline
git checkout 96d244095b1d6c353a48299128871712ce519976
sed -i "s/viash_version: 0\.8\.3/viash_version: 0\.8\.4/g" _viash.yaml
sed -i "s/- path: \/resources_test\/pbmc_1k_protein_v3\/pbmc_1k_protein_v3_filtered_feature_bc_matrix.h5mu//g" ./src/dataflow/split_modalities/config.vsh.yaml
viash ns test -q split_modalities -p native
```

### Expected behavior

Viash should not display an error regarding the missing `_viash.yaml`

### Relevant log output

```
$ viash ns test -q split_modalities -p native
The working directory for the namespace tests is /tmp/viash_ns_test8043643903047300765
           namespace        functionality             platform            test_name exit_code duration               result
            dataflow     split_modalities               native                start                                        
            dataflow     split_modalities               native              test.py         1        2                ERROR
====================================================================
+/tmp/viash_ns_test8043643903047300765/viash_test_split_modalities12044356085658621601/test_test/test_executable
============================= test session starts ==============================
platform linux -- Python 3.11.7, pytest-7.4.4, pluggy-1.3.0
rootdir: /tmp/viash_ns_test8043643903047300765/viash_test_split_modalities12044356085658621601/test_test
plugins: viashpy-0.5.0
collected 1 item

tmp/viash-run-split_modalities-Y4SHkx.py F                               [100%]

=================================== FAILURES ===================================
__________________________________ test_split __________________________________

run_component = <function run_component.<locals>.wrapper at 0x7f857db02c00>
tmp_path = PosixPath('/tmp/pytest-of-di/pytest-31/test_split0')

    def test_split(run_component, tmp_path):
        output_dir = tmp_path / "foo"
        output_types = tmp_path / "foo.csv"
    
>       run_component([
            "--input", input_file,
            "--output", str(output_dir),
            "--output_types", str(output_types),
            "--output_compression", "gzip"
        ])
E       subprocess.CalledProcessError: Command '['viash', 'run', PosixPath('/home/di/code/openpipelines-multisample/src/dataflow/split_modalities/config.vsh.yaml'), '--', '--input', '/tmp/viash_ns_test8043643903047300765/viash_test_split_modalities12044356085658621601/test_test/pbmc_1k_protein_v3_filtered_feature_bc_matrix.h5mu', '--output', '/tmp/pytest-of-di/pytest-31/test_split0/foo', '--output_types', '/tmp/pytest-of-di/pytest-31/test_split0/foo.csv', '--output_compression', 'gzip']' returned non-zero exit status 1.

tmp/viash-run-split_modalities-Y4SHkx.py:37: CalledProcessError
------------------------------ Captured log call -------------------------------
INFO     root:testing.py:176 Captured component output was:
Unexpected error occurred! If you think this is a bug, please post
create an issue at https://github.com/viash-io/viash/issues containing
a reproducible example and the stack trace below.

viash - 0.8.4
Stacktrace:
java.lang.RuntimeException: One of the resources is relative to the project root (/src/authors/dries_schaumont.yaml), but no project config file (_viash.yaml) could be found.
        at io.viash.helpers.IO$.resolveProjectPath(IO.scala:326)
        at io.viash.helpers.circe.RichJson.$anonfun$inherit$3(RichJson.scala:169)
        at scala.collection.immutable.List.map(List.scala:246)
        at io.viash.helpers.circe.RichJson.inherit(RichJson.scala:165)
        at io.viash.helpers.circe.RichJson.$anonfun$inherit$8(RichJson.scala:223)
        at scala.collection.immutable.Vector1.map(Vector.scala:1911)
        at scala.collection.immutable.Vector1.map(Vector.scala:377)
        at io.viash.helpers.circe.RichJson.inherit(RichJson.scala:223)
        at io.viash.helpers.circe.RichJson.$anonfun$inherit$7(RichJson.scala:219)
        at io.circe.JsonObject$MapAndVectorJsonObject.$anonfun$mapValues$1(JsonObject.scala:428)
        at scala.collection.StrictOptimizedMapOps.map(StrictOptimizedMapOps.scala:28)
        at scala.collection.StrictOptimizedMapOps.map$(StrictOptimizedMapOps.scala:27)
        at scala.collection.immutable.HashMap.map(HashMap.scala:39)
        at io.circe.JsonObject$MapAndVectorJsonObject.mapValues(JsonObject.scala:427)
        at io.viash.helpers.circe.RichJson.inherit(RichJson.scala:219)
        at io.viash.helpers.circe.RichJson.$anonfun$inherit$7(RichJson.scala:219)
        at io.circe.JsonObject$MapAndVectorJsonObject.$anonfun$mapValues$1(JsonObject.scala:428)
        at scala.collection.Iterator$$anon$9.next(Iterator.scala:584)
        at scala.collection.mutable.Growable.addAll(Growable.scala:62)
        at scala.collection.mutable.Growable.addAll$(Growable.scala:57)
        at scala.collection.immutable.MapBuilderImpl.addAll(Map.scala:690)
        at scala.collection.immutable.Map$.from(Map.scala:641)
        at scala.collection.immutable.Map$.from(Map.scala:171)
        at scala.collection.MapOps.map(Map.scala:299)
        at scala.collection.MapOps.map$(Map.scala:299)
        at scala.collection.AbstractMap.map(Map.scala:405)
        at io.circe.JsonObject$MapAndVectorJsonObject.mapValues(JsonObject.scala:427)
        at io.viash.helpers.circe.RichJson.inherit(RichJson.scala:219)
        at io.viash.config.Config$.readFromUri(Config.scala:206)
        at io.viash.config.Config$.read(Config.scala:180)
        at io.viash.Main$.readConfig(Main.scala:419)
        at io.viash.Main$.mainCLI(Main.scala:224)
        at io.viash.Main$.mainCLIOrVersioned(Main.scala:123)
        at io.viash.Main$.main(Main.scala:58)
        at io.viash.Main.main(Main.scala)
=========================== short test summary info ============================
FAILED tmp/viash-run-split_modalities-Y4SHkx.py::test_split - subprocess.Call...
============================== 1 failed in 1.42s ===============================

====================================================================
Not all configs built and tested successfully
  114 configs were disabled
  1/1 tests failed
```

```
viash ns test -q split_modalities -p docker
           namespace        functionality             platform            test_name exit_code duration               result
            dataflow     split_modalities               docker                start                                        
The working directory for the namespace tests is /tmp/viash_ns_test15717725429582802082
            dataflow     split_modalities               docker     build_executable         0        1              SUCCESS
            dataflow     split_modalities               docker              test.py         0        5              SUCCESS
Not all configs built and tested successfully
  114 configs were disabled
  2/2 configs built and tested successfully
```

### Version

- OS: Ubuntu 22.04.3 LTS
- Viash version: 0.8.4

### Confirmation

- [X] I have searched the existing issues to make sure this is not a duplicate.
- [X] I have provided clear and concise information about the bug.

**Comment by DriesSchaumont** [comment]
Closing as this is an issue with `viashpy`
