### ISSUE TITLE
File not found message is user unfriendly

### ISSUE THREAD

**Issue by Grifs** [viash-io/viash#71]
When a file is specified that can't be found, viash returns with quite a user unfriendly message, e.g.
```
~/.../resources/testbash >>> viash config view unknown.vsh.yaml             [1]
Exception in thread "main" java.io.FileNotFoundException: [redacted]/testbash/unknown.vsh.yaml (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at scala.io.Source$.fromFile(Source.scala:94)
	at scala.io.Source$.fromFile(Source.scala:79)
	at scala.io.Source$.fromURI(Source.scala:124)
	at com.dataintuitive.viash.helpers.IO$.read(IO.scala:57)
	at com.dataintuitive.viash.config.Config$.readYAML(Config.scala:71)
	at com.dataintuitive.viash.config.Config$.readOnly(Config.scala:112)
	at com.dataintuitive.viash.Main$.main(Main.scala:89)
	at com.dataintuitive.viash.Main.main(Main.scala)
```

This should be caught and returned in a much more succinct way, e.g.
```
~/.../resources/testbash >>> cat unknown.vsh.yaml                           [1]
cat: unknown.vsh.yaml: No such file or directory
```

**Comment by rcannood** [comment]
I'm not sure the last few improvements to the Viash error handling has improved the situation:

```sh
$ URL=https://raw.githubusercontent.com/viash-io/viash_project_template/main/src/demo/remove_comments/config.vsh.yaml
$ viash run $URL \
  -c '.functionality.resources[.path=="script.sh"].path := "foo"' \
  -- --input foo --output foo2

File at URI 'https://raw.githubusercontent.com/viash-io/viash_project_template/main/src/demo/remove_comments/foo' not found
Unexpected error occurred! If you think this is a bug, please post
create an issue at https://github.com/viash-io/viash/issues containing
a reproducible example and the stack trace below.

viash - 0.5.11
Stacktrace:
java.util.NoSuchElementException: None.get
	at scala.None$.get(Option.scala:529)
	at scala.None$.get(Option.scala:527)
	at com.dataintuitive.viash.wrapper.BashWrapper$.wrapScript(BashWrapper.scala:101)
	at com.dataintuitive.viash.platforms.DockerPlatform.modifyFunctionality(DockerPlatform.scala:126)
	at com.dataintuitive.viash.config.Config$.$anonfun$read$4(Config.scala:197)
	at com.dataintuitive.viash.config.Config$.read(Config.scala:215)
	at com.dataintuitive.viash.Main$.readConfig(Main.scala:137)
	at com.dataintuitive.viash.Main$.internalMain(Main.scala:69)
	at com.dataintuitive.viash.Main$.main(Main.scala:38)
	at com.dataintuitive.viash.Main.main(Main.scala)
```

**Comment by Grifs** [comment]
This has been solved some releases ago. It's something to keep an eye on, but closing this issue now.
